[package]
name = "battery-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
notify-rust = "4.8.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_plain = "1.0.1"
