jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --all-features --all
      - run: cargo build --all-features

      - run: cargo clippy --no-default-features --all-targets -- -D warnings
      - run: cargo test --no-default-features --all
      - run: cargo build --no-default-features

on:
  push:
  pull_request:
  workflow_dispatch:
